language: node_js
node_js:
  - '0.10'
services:
  - mongodb
env: DB_URI="mongodb://localhost/mydb_test" PORT=5000 ENV=test
before_script:
  - npm config set ca ""
  - npm start &
deploy:
  - provider: heroku
    api_key:
      secure: HTevOVyDZ+AdyZtmwGLK3rJbmxNvnqveV7v7kQJcuiSiWBJaebcXOWXXlrdeMp8NR2nVr/VXAoQo8PdQbG4KVpo6t/5LcCHjwOJdiGw7Q60Q/dfDupodWhae7BL3DlOH8pwwosjqcLL76xm0+h6og8YjLyY3k5ji1KTcpKeYUkY=
    app:
      online: uos-online
      preview: uos-preview
      dev: uos-dev
    on:
      branch:
        - online
        - preview
        - dev
notifications:
  email: false
