language: node_js
node_js:
  - "0.8"
branches:
  except:
    - master
before_script:
  - wget https://github.com/peachproductions/unitsofsound/archive/master.zip -O client-src.zip
  - unzip -a -q ./client-src.zip -d ./client-src
  - sudo apt-get install -qq unzip
  - mkdir client-src/SDK
  - mkdir www
  - wget http://download.macromedia.com/pub/flex/sdk/flex_sdk_4.6.zip -O ./client-src/SDK/flex_sdk_4.6.zip
  - unzip -a -q ./client-src/SDK/flex_sdk_4.6.zip -d ./client-src/SDK
  - ant -buildfile client-src/build.xml main
deploy:
  provider: nodejitsu
  user: "chrismatheson"
  api_key: "d3c9edaf-4c9b-46de-a1b2-eb54faca6715"
  skip_cleanup: true
notifications:
  email: false