language: node_js
node_js:
    - '0.10'
services:
  - mongodb
env: DB_URI="mongodb://localhost/mydb_test" PORT=5000 ENV=test
before_script:
  - npm config set ca ""
  - npm start &
deploy:
  provider: nodejitsu
  user: chrismatheson
  api_key:
    secure: XodhHlQsJLYJihuoFKJ3cW+g2Cy7uWxG9B6lsmFPpII99XB1gtb++DKF3ZJQj/4PHFikdOr6l6A2RUuef6ssrVCX37lLGROql/D+XP/XYUhjzL5a0eMBmwN2m875Y7q07VFBeUfhrY92NDn3xkLK06lLmNIUI4WerD757M0yHtE=
  skip_cleanup: true
  on:
    branch:
        - master
        - dev
notifications:
  email: false
