---
applications:
  .:
    name: uos-server
    framework:
      name: standalone
      info:
        mem: 64M
        description: Standalone Application
        exec: 
    runtime: node08
    command: node app.js
    infra: aws
    url: ${name}.${target-base} app.unitsofsound.net
    mem: 64M
    instances: 5

